package Interfaces.CompetenciasPantalla;

//import proyecto1.CompetenciaPantallaCrear;
import Interfaces.MenuPrincipalPantalla.MenuPrincipal;


public class CompetenciaPantalla extends javax.swing.JFrame {

    /**
     * Creates new form CompetenciaPantalla
     */
    public CompetenciaPantalla() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CrearBot = new javax.swing.JButton();
        ModificarBot = new javax.swing.JButton();
        EliminarBot = new javax.swing.JButton();
        ListaBot = new javax.swing.JButton();
        RegresarBot = new javax.swing.JButton();
        agregaPruebabot = new javax.swing.JButton();
        elimnaPruebabot = new javax.swing.JButton();
        agregaAtletaBot = new javax.swing.JButton();
        eliminaAtletaBot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel1.setText("Competencia");

        CrearBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CrearBot.setText("Crear Competencia");
        CrearBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBotActionPerformed(evt);
            }
        });

        ModificarBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ModificarBot.setText("Modificar Competencia");
        ModificarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBotActionPerformed(evt);
            }
        });

        EliminarBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EliminarBot.setText("Eliminar Competencia");
        EliminarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotActionPerformed(evt);
            }
        });

        ListaBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ListaBot.setText("Lista de Competencias");
        ListaBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaBotActionPerformed(evt);
            }
        });

        RegresarBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegresarBot.setText("Regresar");
        RegresarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBotActionPerformed(evt);
            }
        });

        agregaPruebabot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agregaPruebabot.setText("Agregar Prueba");
        agregaPruebabot.setToolTipText("");
        agregaPruebabot.setActionCommand("");
        agregaPruebabot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregaPruebabotActionPerformed(evt);
            }
        });

        elimnaPruebabot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        elimnaPruebabot.setText("Eliminar Prueba");
        elimnaPruebabot.setToolTipText("");
        elimnaPruebabot.setActionCommand("");
        elimnaPruebabot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimnaPruebabotActionPerformed(evt);
            }
        });

        agregaAtletaBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agregaAtletaBot.setText("Agregar Atleta");
        agregaAtletaBot.setToolTipText("");
        agregaAtletaBot.setActionCommand("");
        agregaAtletaBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregaAtletaBotActionPerformed(evt);
            }
        });

        eliminaAtletaBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eliminaAtletaBot.setText("Eliminar Atleta");
        eliminaAtletaBot.setToolTipText("");
        eliminaAtletaBot.setActionCommand("");
        eliminaAtletaBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaAtletaBotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegresarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ModificarBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CrearBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EliminarBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ListaBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(agregaPruebabot, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elimnaPruebabot, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregaAtletaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminaAtletaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CrearBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModificarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregaPruebabot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(elimnaPruebabot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregaAtletaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminaAtletaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(RegresarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBotActionPerformed
        this.dispose();
        CompetenciaPantallaCrear CrearP = new CompetenciaPantallaCrear();
        CrearP.setVisible(true);
    }//GEN-LAST:event_CrearBotActionPerformed

    private void ModificarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBotActionPerformed
        this.dispose();
        CompetenciaPantallaModi ModiP = new CompetenciaPantallaModi();
        ModiP.setVisible(true);
    }//GEN-LAST:event_ModificarBotActionPerformed

    private void EliminarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotActionPerformed
        this.dispose();
        CompetenciaPantallaElimi ElimiP = new CompetenciaPantallaElimi();
        ElimiP.setVisible(true);
    }//GEN-LAST:event_EliminarBotActionPerformed

    private void ListaBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaBotActionPerformed
        this.dispose();
        CompetenciaPantallaLista ListaP = new CompetenciaPantallaLista();
        ListaP.setVisible(true);
    }//GEN-LAST:event_ListaBotActionPerformed

    private void RegresarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBotActionPerformed
        this.dispose();
        MenuPrincipal Menu = new MenuPrincipal();
        Menu.setVisible(true);
    }//GEN-LAST:event_RegresarBotActionPerformed

    private void agregaPruebabotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregaPruebabotActionPerformed
        this.dispose();
        CompetenciaPantallaAgregaPrueba AgregaP = new CompetenciaPantallaAgregaPrueba();
        AgregaP.setVisible(true); 
    }//GEN-LAST:event_agregaPruebabotActionPerformed

    private void elimnaPruebabotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimnaPruebabotActionPerformed
        this.dispose();
        CompetenciaPantallaElimiPrueba ElimiP = new CompetenciaPantallaElimiPrueba();
        ElimiP.setVisible(true);
    }//GEN-LAST:event_elimnaPruebabotActionPerformed

    private void agregaAtletaBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregaAtletaBotActionPerformed
        this.dispose();
        CompetenciaPantallaAgregaAtleta agregaP = new CompetenciaPantallaAgregaAtleta();
        agregaP.setVisible(true);
    }//GEN-LAST:event_agregaAtletaBotActionPerformed

    private void eliminaAtletaBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaAtletaBotActionPerformed
        this.dispose();
        CompetenciaPantallaElimiAtleta agregaP = new CompetenciaPantallaElimiAtleta();
        agregaP.setVisible(true);
    }//GEN-LAST:event_eliminaAtletaBotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompetenciaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompetenciaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompetenciaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompetenciaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompetenciaPantalla().setVisible(true);
            }
        });
    }
 //CompetenciaPantallaCrear pantalla = new CompetenciaPantallaCrear();
        //pantalla.setVisible(true);
        
        //this.dispose();
    
    
  // CompetenciaPantallaModi pantalla = new CompetenciaPantallaModi();
      //  pantalla.setVisible(true);
        
       // this.dispose();  
    
//CompetenciaPantallaElimi pantalla = new CompetenciaPantallaElimi();
       // pantalla.setVisible(true);
        
        //this.dispose();    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearBot;
    private javax.swing.JButton EliminarBot;
    private javax.swing.JButton ListaBot;
    private javax.swing.JButton ModificarBot;
    private javax.swing.JButton RegresarBot;
    private javax.swing.JButton agregaAtletaBot;
    private javax.swing.JButton agregaPruebabot;
    private javax.swing.JButton eliminaAtletaBot;
    private javax.swing.JButton elimnaPruebabot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
