
package Interfaces.VisoresAtletasPantalla;

import Interfaces.MenuPrincipalPantalla.MenuPrincipal;
import Lógica.Atleta;
import Lógica.PrincipalAtletismo;
import Lógica.Prueba;
import Lógica.VisorAtleta;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;


public class VisoresPantalla extends javax.swing.JFrame {
        /**
     * Creates new form CorreosPantalla
     */
    public VisoresPantalla() {
        initComponents();
        setLocationRelativeTo(null);
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresarBot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CrearBot = new javax.swing.JButton();
        ModificarBot = new javax.swing.JButton();
        ElimianrBot = new javax.swing.JButton();
        ListaBot = new javax.swing.JButton();
        seguirAtletaBot = new javax.swing.JButton();
        enviarCorreosBot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regresarBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regresarBot.setText("Regresar");
        regresarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBotActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel1.setText("Visores");

        CrearBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CrearBot.setText("Crear Visor");
        CrearBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBotActionPerformed(evt);
            }
        });

        ModificarBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ModificarBot.setText("Modificar Visor");
        ModificarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBotActionPerformed(evt);
            }
        });

        ElimianrBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ElimianrBot.setText("Eliminar Visor");
        ElimianrBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimianrBotActionPerformed(evt);
            }
        });

        ListaBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ListaBot.setText("Lista de Visores");
        ListaBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaBotActionPerformed(evt);
            }
        });

        seguirAtletaBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seguirAtletaBot.setText("Seguir atleta");
        seguirAtletaBot.setActionCommand("");
        seguirAtletaBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguirAtletaBotActionPerformed(evt);
            }
        });

        enviarCorreosBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        enviarCorreosBot.setText("Enviar correos");
        enviarCorreosBot.setActionCommand("");
        enviarCorreosBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCorreosBotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(regresarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ModificarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CrearBot, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ElimianrBot, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seguirAtletaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enviarCorreosBot, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(CrearBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModificarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ElimianrBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seguirAtletaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enviarCorreosBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(regresarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBotActionPerformed
        this.dispose();
        MenuPrincipal Menu = new MenuPrincipal();
        Menu.setVisible(true);
    }//GEN-LAST:event_regresarBotActionPerformed

    private void CrearBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBotActionPerformed
        this.dispose();
        VisorPantallaCrear CrearP = new VisorPantallaCrear();
        CrearP.setVisible(true);
    }//GEN-LAST:event_CrearBotActionPerformed

    private void ModificarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBotActionPerformed
        this.dispose();
        VisorPantallaModi ModiP = new VisorPantallaModi();
        ModiP.setVisible(true);
    }//GEN-LAST:event_ModificarBotActionPerformed

    private void ElimianrBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimianrBotActionPerformed
        this.dispose();
        VisorPantallaElimi ElimiP = new VisorPantallaElimi();
        ElimiP.setVisible(true);
    }//GEN-LAST:event_ElimianrBotActionPerformed

    private void ListaBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaBotActionPerformed
        this.dispose();
        VisorPantallaLista listaP = new VisorPantallaLista();
        listaP.setVisible(true);
    }//GEN-LAST:event_ListaBotActionPerformed

    private void seguirAtletaBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguirAtletaBotActionPerformed
       
        this.dispose();
        VisorPantallaSeguirAtleta SeguirP = new VisorPantallaSeguirAtleta();
        SeguirP.setVisible(true);
    }//GEN-LAST:event_seguirAtletaBotActionPerformed

    private void enviarCorreosBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarCorreosBotActionPerformed
        
        this.dispose();
        
        VisorPantallaCorreos CorreosP = new VisorPantallaCorreos();
        CorreosP.setVisible(true);
        
    }//GEN-LAST:event_enviarCorreosBotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisoresPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisoresPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisoresPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisoresPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisoresPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearBot;
    private javax.swing.JButton ElimianrBot;
    private javax.swing.JButton ListaBot;
    private javax.swing.JButton ModificarBot;
    private javax.swing.JButton enviarCorreosBot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresarBot;
    private javax.swing.JButton seguirAtletaBot;
    // End of variables declaration//GEN-END:variables
}
