package Interfaces.DisciplinasPantalla;

import Interfaces.MenuPrincipalPantalla.MenuPrincipal;
import Interfaces.MenuPrincipalPantalla.MenuPrincipal;

public class DisciplinaPantalla extends javax.swing.JFrame {

    /**
     * Creates new form DisciplinaPantalla
     */
    public DisciplinaPantalla() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CrearDisBot = new javax.swing.JButton();
        ModificarDisBot = new javax.swing.JButton();
        EliminarBot = new javax.swing.JButton();
        ListadoBot = new javax.swing.JButton();
        RegresarBot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel1.setText("Disciplinas");

        CrearDisBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CrearDisBot.setText("Crear disciplina");
        CrearDisBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearDisBotActionPerformed(evt);
            }
        });

        ModificarDisBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ModificarDisBot.setText("Modificar disciplina");
        ModificarDisBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarDisBotActionPerformed(evt);
            }
        });

        EliminarBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EliminarBot.setText("Eliminar disciplina");
        EliminarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotActionPerformed(evt);
            }
        });

        ListadoBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ListadoBot.setText("Lista de disciplinas");
        ListadoBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoBotActionPerformed(evt);
            }
        });

        RegresarBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegresarBot.setText("Regresar");
        RegresarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ModificarDisBot, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CrearDisBot, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegresarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ListadoBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(EliminarBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CrearDisBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ModificarDisBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(EliminarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(ListadoBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(RegresarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearDisBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearDisBotActionPerformed
        this.dispose();
        DisciplinaPantallaCrear CrearP = new DisciplinaPantallaCrear(false);
        CrearP.setVisible(true);     
    }//GEN-LAST:event_CrearDisBotActionPerformed

    private void ModificarDisBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarDisBotActionPerformed
        this.dispose();
        
        DisciplinaPantallaModi ModiP = new DisciplinaPantallaModi();
        ModiP.setVisible(true); 
    }//GEN-LAST:event_ModificarDisBotActionPerformed

    private void EliminarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotActionPerformed
        this.dispose();
        
        DisciplinaPantallaElimi ElimiP = new DisciplinaPantallaElimi();
        ElimiP.setVisible(true); 
    }//GEN-LAST:event_EliminarBotActionPerformed

    private void ListadoBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoBotActionPerformed
        this.dispose();
        DisciplinaPantallaLista listaP = new  DisciplinaPantallaLista();
        listaP.setVisible(true);   
    }//GEN-LAST:event_ListadoBotActionPerformed

    private void RegresarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBotActionPerformed
        this.dispose();
        MenuPrincipal Menu = new MenuPrincipal();
        Menu.setVisible(true);
    }//GEN-LAST:event_RegresarBotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisciplinaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisciplinaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisciplinaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisciplinaPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisciplinaPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearDisBot;
    private javax.swing.JButton EliminarBot;
    private javax.swing.JButton ListadoBot;
    private javax.swing.JButton ModificarDisBot;
    private javax.swing.JButton RegresarBot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
