
package Interfaces.ListadoPantallas;

import Interfaces.MenuPrincipalPantalla.MenuPrincipal;
import Interfaces.MenuPrincipalPantalla.MenuPrincipal;


public class ListadoMarcasPantalla extends javax.swing.JFrame {

    /**
     * Creates new form ListadoMarcasPantalla
     */
    public ListadoMarcasPantalla() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        atletaBot = new javax.swing.JButton();
        mejoresMarcasAtleta = new javax.swing.JButton();
        pruebaBot = new javax.swing.JButton();
        regresarBot = new javax.swing.JButton();
        compenteciaBot1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel1.setText("Listado de marcas por:");

        atletaBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atletaBot.setText("Atleta");
        atletaBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atletaBotActionPerformed(evt);
            }
        });

        mejoresMarcasAtleta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mejoresMarcasAtleta.setText("Mejores marcas del atleta");
        mejoresMarcasAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejoresMarcasAtletaActionPerformed(evt);
            }
        });

        pruebaBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pruebaBot.setText("Prueba");
        pruebaBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pruebaBotActionPerformed(evt);
            }
        });

        regresarBot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regresarBot.setText("Regresar");
        regresarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBotActionPerformed(evt);
            }
        });

        compenteciaBot1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        compenteciaBot1.setText("Compentencias");
        compenteciaBot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compenteciaBot1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mejoresMarcasAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(pruebaBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atletaBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compenteciaBot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresarBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(compenteciaBot1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atletaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pruebaBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mejoresMarcasAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(regresarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atletaBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atletaBotActionPerformed
        this.dispose();
        ListadoBuscarAtleta ListaAtle = new ListadoBuscarAtleta(0);
        ListaAtle.setVisible(true);
    }//GEN-LAST:event_atletaBotActionPerformed

    private void mejoresMarcasAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejoresMarcasAtletaActionPerformed
        this.dispose();
        ListadoBuscarAtleta ListaMejoresMarcas = new ListadoBuscarAtleta(1);
        ListaMejoresMarcas.setVisible(true);
    }//GEN-LAST:event_mejoresMarcasAtletaActionPerformed

    private void pruebaBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pruebaBotActionPerformed
        this.dispose();
        ListadoBuscarPrueba buscaP = new ListadoBuscarPrueba();
        buscaP.setVisible(true);
    }//GEN-LAST:event_pruebaBotActionPerformed

    private void regresarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBotActionPerformed
        this.dispose();
        MenuPrincipal Menu = new MenuPrincipal();
        Menu.setVisible(true);
    }//GEN-LAST:event_regresarBotActionPerformed

    private void compenteciaBot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compenteciaBot1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ListadoBuscarCompe ListaAtle = new ListadoBuscarCompe();
        ListaAtle.setVisible(true);
    }//GEN-LAST:event_compenteciaBot1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoMarcasPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoMarcasPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoMarcasPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoMarcasPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoMarcasPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atletaBot;
    private javax.swing.JButton compenteciaBot1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mejoresMarcasAtleta;
    private javax.swing.JButton pruebaBot;
    private javax.swing.JButton regresarBot;
    // End of variables declaration//GEN-END:variables
}
